START TRANSACTION;

CREATE TABLE "SeriesData"
(
    "SeriesId" bigint NOT NULL,
    "Dt"       bigint NOT NULL,
    "Value"    jsonb NULL,
    CONSTRAINT "PK_SeriesData" PRIMARY KEY ("SeriesId", "Dt")
);

CREATE TABLE "Tag"
(
    "SeriesId"     bigint GENERATED BY DEFAULT AS IDENTITY,
    "PartitionKey" uuid NOT NULL,
    "TagName"      text NOT NULL,
    CONSTRAINT "PK_Tag" PRIMARY KEY ("SeriesId")
);

CREATE TABLE "TagMetaData"
(
    "SeriesId"      bigint NOT NULL,
    "MetaDataKey"   text   NOT NULL,
    "MetaDataValue" text   NOT NULL,
    CONSTRAINT "PK_TagMetaData" PRIMARY KEY ("SeriesId", "MetaDataKey"),
    CONSTRAINT "FK_TagMetaData_Tag_SeriesId" FOREIGN KEY ("SeriesId") REFERENCES "Tag" ("SeriesId") ON DELETE CASCADE
);

CREATE INDEX "IX_Tag_PartitionKey_TagName" ON "Tag" ("PartitionKey", "TagName");

COMMIT;